log:
  level: debug
  disable_sentry: true

db:
  url: pg_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: verificator-svc
  service_port: 80

callback:
  url: "http://localhost:8000"

verifier:
  verification_key_path: "./proof_keys/passport.json"
  allowed_identity_timestamp: 1715698750
  event_id: "event_id"

poseidonsmt_root_verifier:
  rpc: rpc_url
  contract: contract_address
  request_timeout: 10s