allOf:
  - $ref: '#/components/schemas/ParametersKey'
  - type: object
    required:
      - attributes
    properties:
      attributes:
        type: object
        required:
          - event_id
          - event_data
          - selector
          - identity_counter
          - timestamp_lower_bound
          - timestamp_upper_bound
          - identity_counter_lower_bound
          - identity_counter_upper_bound
          - expiration_date_lower_bound
          - expiration_date_upper_bound
          - birth_date_lower_bound
          - birth_date_upper_bound
          - citizenship_mask
          - callback_url
        properties:
          event_id:
            type: string
          event_data:
            type: string
          selector:
            type: string
          identity_counter:
            type: integer
          timestamp_lower_bound:
            type: string
          timestamp_upper_bound:
            type: string
          identity_counter_lower_bound:
            type: integer
          identity_counter_upper_bound:
            type: integer 
          expiration_date_lower_bound:
            type: string
          expiration_date_upper_bound:
            type: string
          birth_date_lower_bound:
            type: string
          birth_date_upper_bound:
            type: string
          citizenship_mask:
            type: string          
          callback_url:
            type: string
            example: "https://example.com/integrations/verificator-svc/public/receive-proof/callback/c15ad8f88949"